version: '3'

services:
  api:
    container_name: api-service
    build:
      context: .
      dockerfile: ./docker/backend/development/Dockerfile
    volumes:
      - ./backend:/usr/src/app
    tty: true
    ports:
      - "4000:4000"