import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import MembersList from '@/components/Members/MembersList'
import CreateMember from '@/components/Members/CreateMember'
import ToggleTheme from '@/components/Theme/ToggleTheme'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          戦闘員
        </h1>

        <div className={styles.grid}>
          <MembersList />
          <CreateMember />
        </div>
      </main>

      <footer className={styles.footer}>
        <ToggleTheme /> Powered by YT-NKGW
      </footer>
    </div>
  )
}

export default Home
